### PR TITLE
update social idp list

### PR DESCRIPTION
**Pull request by zhongyn**

### CODE REVIEW

**Comment by stanleyymsft** [comment]
Should we add "中国区暂不支持 Google, Facebook, Twitter 作为标识提供者。" to weibo and QQ page too?  Or add another page calling out non-supported IdP's so we don't have to repeat it?

**Comment by zhongyn** [comment]
will try if adding a new page works

**Comment by forester123** [comment]
@stanleyymsft @zhongyn Thank you for the feedback! The changes look good to me. Besides, for the three  new docs you update in the TOC.yml , may I know if you are working on them?

**Comment by forester123** [comment]
@zhongyn please ignore my previous comments, I think I misunderstood your update for the TOC file, your changes are approved. Thanks a lot for your contribution!

**Pull request merged**
